### ISSUE TITLE
To create a distribution for Zef ecosystem, you need to install fez first

### ISSUE THREAD

**Issue by melezhik** [tbrowder/Mi6-Helper#4]
Hi! I have created a simple CICD pipeline for Mi6-Helper, a smoke test says - "To create a distribution for Zef ecosystem, you need to install fez first" even though when zef is installed. Or maybe I miss something in my test?

The full log is here - https://ci.sparrowhub.io/report/1350

HTH

Alexey

**Comment by tbrowder** [comment]
Notice added. Thanks!

**Comment by melezhik** [comment]
👍
